# Generated by Django 5.0.3 on 2024-04-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_item_checkout_delete_checkin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='item',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='CheckOut',
        ),
    ]
